### PR TITLE
add hideNav and hideNext

### PR DESCRIPTION
**Pull request by hkjeffchan**
Add hideNav and hideNext so that we can enforce the user to use "focusClick" to step forward

### CODE REVIEW

**Comment by Zefling** [comment]
Would it be possible to use Prettier's formatter?

**Comment by hkjeffchan** [comment]
> Would it be possible to use Prettier's formatter?

already using the latest version from https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by Zefling** [comment]
With this line in the setting.json?
```json
{
   "editor.defaultFormatter": "esbenp.prettier-vscode",
}
```

**Comment by hkjeffchan** [comment]
Just found that I am using another formatter for html. Formatted with prettier now. Thanks!

**Comment by Zefling** [comment]
Thanks.

**Comment by hkjeffchan** [comment]
It will be great if you can publish the changes to npm as a new version. Thanks!

**Comment by Zefling** [comment]
Sorry, tomorrow, no time today.

**Comment by Zefling** [comment]
:rocket:

**Pull request merged**
